apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: node-chrome-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 7
    labels:
      app: node-chrome
    name: node-chrome
  spec:
    replicas: 2
    selector:
      app: node-chrome
      deploymentconfig: node-chrome
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/container.node-chrome.image.entrypoint: '["/opt/bin/entry_point.sh"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: node-chrome
          deploymentconfig: node-chrome
      spec:
        containers:
        - image: ${OC_REPO}/${NAMESPACE}/node-chrome
          imagePullPolicy: Always
          name: node-chrome
          resources:
            limits:
              cpu: 1500m
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /dev/shm
            name: node-chrome-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: node-chrome-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - node-chrome
        from:
          kind: ImageStreamTag
          name: node-chrome:latest
          namespace: devops-infra
      type: ImageChange

